---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  machine:
    image: ubuntu-1604:201903-01
workflows:
  version: 2
  checkout_build_install:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install development package(s)
          command: sudo apt install -y libelf-dev
      - run: KDIR=/lib/modules/$(uname -r)/build make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install development package(s)
          command: sudo apt install -y libelf-dev
      - run: KDIR=/lib/modules/$(uname -r)/build sudo make install
