---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  machine:
    image: circleci/classic:edge
workflows:
  version: 2
  checkout_build_install:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source
          command: sudo apt install -y linux-headers-$(uname -r)
      - persist_to_workspace:
          root: /
          paths:
            - usr/src/linux-headers-$(uname -r)
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KDIR=/usr/src/linux-headers-$(uname -r) make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Install kernel source code
          command: sudo apt install -y linux-headers-$(uname -r)
      - run: KDIR=/usr/src/linux-headers-$(uname -r) sudo -E make install
