---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: keinohguchi/archlinux
workflows:
  version: 2
  checkout_build_install:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source code
          command: |
            pacman -Sy --noconfirm linux linux-headers
      - persist_to_workspace:
          root: /
          paths:
            - lib/modules/
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build make install
