---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: gcc:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source code
          command: |
            apt update
            apt install -y linux-image-amd64
      - persist_to_workspace:
          root: /
          paths:
            - lib/modules/
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KERNDIR=$(ls -d /lib/modules/*-amd64|head -1)/build make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KERNDIR=$(ls -d /lib/modules/*-amd64|head -1)/build sudo -E make install
