---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: keinohguchi/archlinux
workflows:
  version: 2
  checkout_build_install:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source code and the build tools
          command: |
            pacman -S --noconfirm linux linux-headers gcc make grep
      - persist_to_workspace:
          root: /
          paths:
            - lib/modules/
            - usr/bin/as
            - usr/bin/ld
            - usr/bin/gcc
            - usr/bin/make
            - usr/bin/grep
            - usr/lib/libopcodes-*
            - usr/lib/libbfd-*
            - usr/lib/libgc.so*
            - usr/lib/libmpc.so*
            - usr/lib/libmpfr.so*
            - usr/lib/libltdl.so*
            - usr/lib/libguile-2.2.so*
            - usr/lib/gcc/x86_64-pc-linux-gnu
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build make install
