---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: gcc:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - load:
          requires:
            - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source code
          command: |
            apt update
            apt install -y linux-source
      - persist_to_workspace:
          root: /
          paths:
            - lib/modules/$(uname -r)
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make
  load:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make load
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make test
