---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: archlinux/base:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - install:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install kernel source code and the build tools
          command: |
            pacman -Sy
            pacman -S --noconfirm linux linux-headers gcc make
      - persist_to_workspace:
          root: /
          paths:
            - lib/modules/
            - usr/bin/gcc
            - usr/bin/make
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KERNDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build make
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: KERNDIR=$(ls -d /lib/modules/*-ARCH|head -1)/build sudo -E make install
