---
version: 2
default: &defaults
  working_directory: /home/circleci/project/ldd
  docker:
    - image: archlinux/base:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - load:
          requires:
            - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install base commands
          command: |
            pacman -S --noconfirm gcc
      - persist_to_workspace:
          root: /
          paths:
            - usr/bin/gcc
            - home/circleci/project/ldd
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make
  load:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make load
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make test
